### ISSUE TITLE
help...Can I save the connectome file or seed correlation map not only the picture in the cifti_vis_PINT ?

### ISSUE THREAD

**Issue by DearBraveJohn** [edickie/ciftify#103]

**Comment by DearBraveJohn** [comment]
Can the cifti_vis_PINT save all the source file of the QC_PINT picture, and my QC file have a little bit wired like that the border separate the network looks like not in the right place.
![image](https://user-images.githubusercontent.com/33821965/55047086-817c0200-507e-11e9-9eae-30a39ce70c81.png)

**Comment by edickie** [comment]
Thanks for the catch! I really _hope_ this is just a plotting error (i.e.
with the white lines). Will troubleshoot this weekend.

**Comment by edickie** [comment]
Thanks for catching this. It looks like it is due to a difference in seaborn/matplotlib's plotting behaviour. Will fix in the next release.

The underlying data from these plots are in the csv's from the PINT outputs. The heatmaps are generated by calculating a simple (full pearson's) correlation on the timeseries that are output in the `_pvertex_meants.csv` and `_tvertex_meants.csv` output files. (Note the `_meants.csv` outputs have "ROI" as rows and TR as columns). The ROI order and network is given in the `_summary.csv` files and should match those in the input "template" file (i.e. Yeo7_2011_80verts.csv).

**Comment by DearBraveJohn** [comment]
Thanks for the answer, Erin. Really appreciate your help
