### ISSUE TITLE
not running... probably a beginner's mistake.

### ISSUE THREAD

**Issue by jcrdubois** [edickie/ciftify#97]
Hi Erin

thanks for the suggestion to use your work to convert fmriprep outputs to HCP-like outputs.

I just installed ciftify on my ubuntu 16.04; I'm trying it out, but can't get it to run yet. Here is the command:
$ ciftify_recon_all \
--ciftify-work-dir /data/MRI/YALE-trt/derivatives/hcp \
--fs-subjects-dir /data/MRI/YALE-trt/derivatives/freesurfer \
--resample-to-T1w32k \
--surf-reg MSMSulc \
--fs-license /usr/local/freesurfer/license.txt \
--n_cpus 20 \
--debug \
sub-032401

which outputs the following:
Usage:
  ciftify_recon_all [options] <Subject>

as if I made a mistake in the command line. I probably did, but I can't see where. Help?
Thanks!
- Julien

**Comment by edickie** [comment]
Weird, your right that it is definitely a command-line usage error. But the
command looks correct to me.. Maybe there's a hidden carriage return? What
happens when you echo the line?

Also, is there a reason you are using the functions by themselves instead
of the docker runner? The docker runner _should_ detect the fmriprep and
freesurfer outputs and only perform the extra HCP conversion if you set the
"output" to the derivatives directory.. Although that only works for
fmriprep < 2.0 at the moment.

Sorry I couldn't be more the help.
Erin

**Comment by jcrdubois** [comment]
Hi Erin

after some trial and error I got the command to run, by removing the following arguments:
```
--surf-reg MSMSulc 
--fs-license /usr/local/freesurfer/license.txt 
```

Re: the docker runner: I have already run fmriprep 1.2.5. How would I run ciftify?

- Julien

**Comment by edickie** [comment]
Ooooh I that makes sense. The I may not have pushed the version with the
--fs-license option to pypi yet.  Either way, the '--surf-reg MSMSulc' is
the default (so it should run the same) and the --fs-license flag should
not be required if freesurfer already set up in the environment. So that
makes sense.

The ciftify runner still only expects the old fmriprep output filenames
(i.e. 1.1.8 and earlier) so I guess you will need to run the steps
manually.   i.e. once ciftify_recon_all has run you need to then call
ciftify_subject_fmri on each preprocessed fMRI file. There's a little bit
of info towards that here
https://edickie.github.io/ciftify/#/tutorials/example-usage. Let me know if
anything is unclear.

Thanks,
Erin

**Comment by jcrdubois** [comment]
excellent. Thanks Erin! I'll be watching ciftify for future releases, in the meantime I'll run things in my own prepared environment. Great work!
